### ISSUE TITLE
Support signed commits

### ISSUE THREAD

**Issue by hiwelo** [cirrus-actions/rebase#37]
When using this script as a _GitHub Action_ in one of the project I lead at work, the action is removing the signature associated to a commit when doing a rebase.

In order to merge a PR, we require that all commits are signed so I would like to know if there is a way to:
1. either keep each commit signed
2. or to sign the new commits during the rebase

We can see this issue in the screen recording part of the `README.md` file of this repository.

![Screenshot of a recording of this script working in a pull request](https://user-images.githubusercontent.com/4989733/73654870-036c8c80-468d-11ea-844f-ffd9978000c7.png)

**Comment by fkorotkov** [comment]
I'm not quite sure if it's possible. When a branch is rebased the `git rebase` command is essentially re-applying commits which might end up in a different content since conflict resolution. Therefore these new commits should be re-signed again but the action won't be able to get the keys to sign it.

My current understanding of how Git works and also quick googling didn't help to help a workaround to that issue. If anyone knows a way to rebase with saving the signature I would happily add it to `entrypoint.sh`. 😪

**Comment by hiwelo** [comment]
Thank you for your answer, I was a bit fearing this to be honest.
My understanding (or lack of 😄) is driving me to the same conclusion 😅

I would expect the only way to be a fully custom script run by an environment we control having a key to sign commits :)

**Comment by ROSAISS81** [comment]
<commit_sha>

**Comment by Lachann** [comment]
Wouldn't it be possible to at least have a bot signature on the commit?

**Comment by imminent** [comment]
> Wouldn't it be possible to at least have a bot signature on the commit?

any answer for how to use the bot signature @Lachann suggested? I found https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c in searching that topic
