### ISSUE TITLE
Support for PRs from forks works for some but not others

### ISSUE THREAD

**Issue by vorburger** [cirrus-actions/rebase#48]
Following up on #12: (@drdanz @fkorotkov @sobolevn @ljharb @gep13 perhaps this interests you)

I'm a bit puzzled about why `/rebase` works for us e.g. on https://github.com/apache/fineract/pull/769 (see [the Action's run here](https://github.com/apache/fineract/actions/runs/113304897)) but failed e.g. for https://github.com/apache/fineract/pull/825 (see [here](https://github.com/apache/fineract/runs/702185407) and [here](https://github.com/apache/fineract/runs/702179667) failing due to "error: failed to push some refs").

**Comment by gep13** [comment]
@vorburger I can't see this information on your PR's since I am not a contributor, but do you see something like the following:

![image](https://user-images.githubusercontent.com/1271146/82734845-699d1e00-9d15-11ea-9a15-3783d9f1e3a6.png)

On the PR that is successfully being rebased?  Do you also see it on the PR that isn't working?

**Comment by fkorotkov** [comment]
Maybe @nazeer1100126 didn't allow for contributors to push back to his fork in https://github.com/apache/fineract/pull/825

**Comment by fkorotkov** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by vorburger** [comment]
Yeah, that's it! 

_"Add more commits by pushing to the ... branch on ..."_

Thank You for elaborating on this so clearly with screenshot and link.
